name: CM3070
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.9
  - pip=22.3.1

  - autopep8=2.0.1
  - fastapi=0.89.1
  - pyyaml=6.0
  - uvicorn=0.20.0
  - pytest=7.2.1
  - pytest-cov=4.0.0
  - pylint=2.15.10
  - bandit=1.7.4
  - httpx=0.23.3
  - python-dotenv=0.21.1
  - pycuda=2022.2.2
  - cudatoolkit=11.8.0
  - cudnn=8.4.1.50
  - pymemcache=4.0.0
  - pandas=1.5.3
  - optuna=3.1.0
  - dependency_injector=4.41.0
  - scipy=1.10.1

  - pip:
    - torch==1.13.1
    - pytorch-lightning==1.6.5
    - prisma==0.7.1
    - super_hash==1.2.6
    - torch-tb-profiler==0.4.1