version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  db:
    image: memcached:1.6.18
    restart: unless-stopped
    
volumes:
  mongodb-data: